pipeline {
	agent any
	stages {
		stage('Clean stage') {
			steps {
				dir("stocksapp") {
					bat 'mvn clean'
				}
			}
		}
		stage('Compile stage') {
			steps {
				dir("stocksapp") {
					bat 'mvn compile'
				}
			}
		}
		stage('Install stage') {
			steps {
				dir("stocksapp") {
					bat 'mvn install'
				}
			}
		}
		stage('Deploy stage') {
			steps {
				dir("stocksapp/target") {
					withEnv(['JENKINS_NODE_COOKIE=DontKillMe']) {
						bat 'start java -Dserver.port=3000 -jar TransferFundsApp-0.0.1-SNAPSHOT.jar'
					}
				}
			}
		}
	}
}
