pipeline {
	agent any
	stages {
		stage('Clean stage') {
			steps {
				dir("StockPricesApp") {
					bat 'mvn clean'
				}
			}
		}
		stage('Compile stage') {
			steps {
				dir("StockPricesApp") {
					bat 'mvn compile'
				}
			}
		}
		
	}
}
